version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: booking_postgres_dev
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: ticket_booking_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: booking_redis_dev
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: booking_rabbitmq_dev
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpassword

volumes:
  postgres_data_dev: